sonar.projectKey=trungenglish_TorungPhim_BE
sonar.organization=trungenglish-testing

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=TorungPhim_BE
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts

# Exclude node_modules and other unnecessary files
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8